INSERT INTO products (
    name,
    size,
    price,
    description,
    height,
    width,
    weight,
    length,
    color,
    url_image,
    amount,
    category_id
)
VALUES
    (
        'Candle Lunar',
        'S',
        220,
        'Sculptural and serene, Lunar embraces light within its soft curves. A modern centerpiece that brings warmth and balance to any space.',
        8,
        8,
        280,
        8,
        'Light Grey',
        '/images/products/candles/candle_1.jpg',
        18,
        6
    ),
    (
        'Candle Orbit',
        'M',
        130,
        'Inspired by celestial motion, Orbit features a smooth, rounded form that cradles light beautifully. Perfect for modern, minimalist interiors.',
        10,
        9,
        350,
        9,
        'Warm Grey',
        '/images/products/candles/candle_2.jpg',
        14,
        6
    ),
    (
        'Candle Haven',
        'L',
        90,
        'A cozy retreat for candlelight. Haven’s organic shape creates a calming atmosphere, adding a touch of natural elegance to your home.',
        13,
        11,
        480,
        11,
        'Sand',
        '/images/products/candles/candle_3.jpg',
        11,
        6
    ),
    (
        'Candle Eclipse',
        'XL',
        170,
        'Bold and balanced, Eclipse plays with contrast and form. Its unique silhouette casts captivating shadows, elevating your décor effortlessly.',
        16,
        13,
        620,
        13,
        'Charcoal Grey',
        '/images/products/candles/candle_4.jpg',
        7,
        6
    ),
    (
        'Candle Nimbus',
        'M',
        250,
        'Light as a cloud, strong as stone. Nimbus combines soft curves with a solid presence, bringing tranquility and sophistication to any setting.',
        11,
        10,
        410,
        10,
        'Stone Grey',
        '/images/products/candles/candle_5.jpg',
        12,
        6
    ),
    (
        'Candle Aurea',
        'L',
        140,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        14,
        12,
        520,
        12,
        'Ivory',
        '/images/products/candles/candle_6.jpg',
        9,
        6
    ),
    (
        'Candle Soleil',
        'S',
        110,
        'Radiant and uplifting, Soleil captures the essence of sunlight. Its open form spreads warmth and creates a bright, welcoming ambiance.',
        7,
        9,
        260,
        9,
        'Cream',
        '/images/products/candles/candle_7.jpg',
        20,
        6
    ),
    (
        'Candle Terra',
        'XL',
        90,
        'Grounded in natural beauty, Terra celebrates earthy textures and organic shapes. A perfect blend of raw material and modern design.',
        17,
        14,
        680,
        14,
        'Terracotta',
        '/images/products/candles/candle_8.jpg',
        6,
        6
    ),
    (
        'Candle Zenith',
        'M',
        95,
        'Elevate your space with Zenith. Its clean lines and balanced form symbolize harmony and clarity, ideal for peaceful, modern living.',
        12,
        10,
        430,
        10,
        'Off White',
        '/images/products/candles/candle_9.jpg',
        13,
        6
    ),
    (
        'Candle Nova',
        'L',
        110,
        'Modern and striking, Nova is designed to stand out. Its dynamic shape reflects contemporary style and artistic expression.',
        15,
        12,
        570,
        12,
        'Graphite',
        '/images/products/candles/candle_10.jpg',
        8,
        6
    ),
    (
        'Candle Drift',
        'S',
        150,
        'Inspired by natural movement, Drift flows effortlessly. Its smooth contours bring a sense of calm and organic beauty to your space.',
        9,
        8,
        300,
        8,
        'Beige',
        '/images/products/candles/candle_11.jpg',
        16,
        6
    ),
    (
        'Candle Cosmo',
        'XL',
        110,
        'Cosmo brings a touch of the universe into your home. Its sculptural form and soft texture create a modern, cosmic charm.',
        18,
        15,
        750,
        15,
        'Dark Grey',
        '/images/products/candles/candle_12.jpg',
        5,
        6
    ),
    (
        'Candle Mira',
        'M',
        160,
        'Elegant and minimal, Mira reflects light beautifully. Its refined shape complements any interior with understated sophistication.',
        10,
        11,
        390,
        11,
        'Pearl White',
        '/images/products/candles/candle_13.jpg',
        15,
        6
    ),
    (
        'Candle Solace',
        'L',
        150,
        'Find peace in simplicity. Solace offers a gentle, embracing form that enhances relaxation and creates a warm, comforting atmosphere.',
        13,
        12,
        510,
        12,
        'Taupe',
        '/images/products/candles/candle_14.jpg',
        10,
        6
    );