INSERT INTO products (
    name,
    size,
    price,
    description,
    height,
    width,
    weight,
    length,
    color,
    url_image,
    amount,
    category_id
)
VALUES
    (
        'Pebbles Lunar',
        'S',
        210,
        'Sculptural and serene, Lunar embraces light within its soft curves. A modern centerpiece that brings warmth and balance to any space.',
        5,
        8,
        180,
        9,
        'Light Grey',
        '/images/products/pebbles/pebbles_1.jpg',
        25,
        4
    ),
    (
        'Pebbles Orbit',
        'M',
        250,
        'Inspired by celestial motion, Orbit features a smooth, rounded form that cradles light beautifully. Perfect for modern, minimalist interiors.',
        6,
        10,
        240,
        11,
        'Warm Grey',
        '/images/products/pebbles/pebbles_2.jpg',
        20,
        4
    ),
    (
        'Pebbles Haven',
        'L',
        160,
        'A cozy retreat for candlelight. Haven’s organic shape creates a calming atmosphere, adding a touch of natural elegance to your home.',
        8,
        12,
        320,
        14,
        'Sand',
        '/images/products/pebbles/pebbles_3.jpg',
        16,
        4
    ),
    (
        'Pebbles Eclipse',
        'XL',
        130,
        'Bold and balanced, Eclipse plays with contrast and form. Its unique silhouette casts captivating shadows, elevating your décor effortlessly.',
        10,
        15,
        450,
        17,
        'Charcoal Grey',
        '/images/products/pebbles/pebbles_4.jpg',
        10,
        4
    ),
    (
        'Pebbles Nimbus',
        'M',
        350,
        'Light as a cloud, strong as stone. Nimbus combines soft curves with a solid presence, bringing tranquility and sophistication to any setting.',
        7,
        11,
        280,
        13,
        'Stone Grey',
        '/images/products/pebbles/pebbles_5.jpg',
        18,
        4
    ),
    (
        'Pebbles Aurea',
        'L',
        330,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        9,
        13,
        360,
        15,
        'Ivory',
        '/images/products/pebbles/pebbles_6.jpg',
        12,
        4
    );