INSERT INTO products (
    name,
    size,
    price,
    description,
    height,
    width,
    weight,
    length,
    color,
    url_image,
    amount,
    category_id
)
VALUES
    (
        'Bowl Lunar',
        'S',
        150,
        'Sculptural and serene, Lunar embraces light within its soft curves. A modern centerpiece that brings warmth and balance to any space.',
        7,
        16,
        620,
        16,
        'Light Grey',
        '/images/products/bowls/bowl_1.jpg',
        14,
        5
    ),
    (
        'Bowl Orbit',
        'M',
        160,
        'Inspired by celestial motion, Orbit features a smooth, rounded form that cradles light beautifully. Perfect for modern, minimalist interiors.',
        9,
        20,
        850,
        20,
        'Warm Grey',
        '/images/products/bowls/bowl_2.jpg',
        11,
        5
    ),
    (
        'Bowl Haven',
        'L',
        250,
        'A cozy retreat for candlelight. Haven’s organic shape creates a calming atmosphere, adding a touch of natural elegance to your home.',
        11,
        24,
        1050,
        24,
        'Sand',
        '/images/products/bowls/bowl_3.jpg',
        8,
        5
    ),
    (
        'Bowl Eclipse',
        'XL',
        190,
        'Bold and balanced, Eclipse plays with contrast and form. Its unique silhouette casts captivating shadows, elevating your décor effortlessly.',
        14,
        28,
        1350,
        28,
        'Charcoal Grey',
        '/images/products/bowls/bowl_4.jpg',
        6,
        5
    ),
    (
        'Bowl Nimbus',
        'M',
        240,
        'Light as a cloud, strong as stone. Nimbus combines soft curves with a solid presence, bringing tranquility and sophistication to any setting.',
        8,
        19,
        780,
        19,
        'Stone Grey',
        '/images/products/bowls/bowl_5.jpg',
        12,
        5
    ),
    (
        'Bowl Aurea',
        'L',
        310,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        10,
        23,
        980,
        23,
        'Ivory',
        '/images/products/bowls/bowl_6.jpg',
        9,
        5
    ),
    (
        'Bowl Soleil',
        'S',
        240,
        'Radiant and uplifting, Soleil captures the essence of sunlight. Its open form spreads warmth and creates a bright, welcoming ambiance.',
        6,
        15,
        560,
        15,
        'Cream',
        '/images/products/bowls/bowl_7.jpg',
        16,
        5
    ),
    (
        'Bowl Terra',
        'XL',
        190,
        'Grounded in natural beauty, Terra celebrates earthy textures and organic shapes. A perfect blend of raw material and modern design.',
        15,
        30,
        1480,
        30,
        'Terracotta',
        '/images/products/bowls/bowl_8.jpg',
        5,
        5
    ),
    (
        'Bowl Zenith',
        'M',
        240,
        'Elevate your space with Zenith. Its clean lines and balanced form symbolize harmony and clarity, ideal for peaceful, modern living.',
        9,
        21,
        890,
        21,
        'Off White',
        '/images/products/bowls/bowl_9.jpg',
        10,
        5
    );