INSERT INTO products (
    name,
    size,
    price,
    description,
    height,
    width,
    weight,
    length,
    color,
    url_image,
    amount,
    category_id
)
VALUES
    (
        'Planter Lunar',
        'S',
        150,
        'Sculptural and serene, Lunar embraces light within its soft curves. A modern centerpiece that brings warmth and balance to any space.',
        18,
        10,
        90,
        10,
        'Light Grey',
        '/images/products/planters/planter_1.jpg',
        14,
        3
    ),
    (
        'Planter Orbit',
        'M',
        230,
        'Inspired by celestial motion, Orbit features a smooth, rounded form that cradles light beautifully. Perfect for modern, minimalist interiors.',
        25,
        12,
        120,
        12,
        'Warm Grey',
        '/images/products/planters/planter_2.jpg',
        10,
        3
    ),
    (
        'Planter Haven',
        'L',
        130,
        'A cozy retreat for candlelight. Haven’s organic shape creates a calming atmosphere, adding a touch of natural elegance to your home.',
        32,
        16,
        180,
        16,
        'Stone Grey',
        '/images/products/planters/planter_3.jpg',
        7,
        3
    ),
    (
        'Planter Eclipse',
        'M',
        250,
        'Bold and balanced, Eclipse plays with contrast and form. Its unique silhouette casts captivating shadows, elevating your décor effortlessly.',
        27,
        14,
        145,
        14,
        'Charcoal Grey',
        '/images/products/planters/planter_4.jpg',
        8,
        3
    ),
    (
        'Planter Nimbus',
        'XL',
        250,
        'Light as a cloud, strong as stone. Nimbus combines soft curves with a solid presence, bringing tranquility and sophistication to any setting.',
        40,
        20,
        260,
        20,
        'Cloud Grey',
        '/images/products/planters/planter_5.jpg',
        5,
        3
    ),
    (
        'Planter Aurea',
        'S',
        110,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        20,
        11,
        100,
        11,
        'Sand',
        '/images/products/planters/planter_6.jpg',
        12,
        3
    ),
    (
        'Planter Soleil',
        'L',
        230,
        'Radiant and uplifting, Soleil captures the essence of sunlight. Its open form spreads warmth and creates a bright, welcoming ambiance.',
        34,
        17,
        195,
        17,
        'Ivory',
        '/images/products/planters/planter_7.jpg',
        6,
        3
    ),
    (
        'Planter Terra',
        'M',
        90,
        'Grounded in natural beauty, Terra celebrates earthy textures and organic shapes. A perfect blend of raw material and modern design.',
        24,
        13,
        135,
        13,
        'Taupe',
        '/images/products/planters/planter_8.jpg',
        9,
        3
    ),
    (
        'Planter Zenith',
        'XL',
        90,
        'Elevate your space with Zenith. Its clean lines and balanced form symbolize harmony and clarity, ideal for peaceful, modern living.',
        42,
        22,
        290,
        22,
        'Dark Grey',
        '/images/products/planters/planter_9.jpg',
        4,
        3
    ),
    (
        'Planter Nova',
        'S',
        120,
        'Modern and striking, Nova is designed to stand out. Its dynamic shape reflects contemporary style and artistic expression.',
        19,
        10,
        95,
        10,
        'White',
        '/images/products/planters/planter_10.jpg',
        15,
        3
    );