INSERT INTO products (
    name,
    size,
    price,
    description,
    height,
    width,
    weight,
    length,
    color,
    url_image,
    amount,
    category_id
)
VALUES
    (
        'Tray Lunar',
        'S',
        130,
        'Sculptural and serene, Lunar embraces light within its soft curves. A modern centerpiece that brings warmth and balance to any space.',
        4,
        25,
        280,
        18,
        'Light Grey',
        '/images/products/trays/tray_1.jpg',
        14,
        2
    ),
    (
        'Tray Orbit',
        'M',
        145,
        'Inspired by celestial motion, Orbit features a smooth, rounded form that cradles light beautifully. Perfect for modern, minimalist interiors.',
        5,
        30,
        350,
        22,
        'Warm Grey',
        '/images/products/trays/tray_2.jpg',
        11,
        2
    ),
    (
        'Tray Haven',
        'L',
        155,
        'A cozy retreat for candlelight. Haven’s organic shape creates a calming atmosphere, adding a touch of natural elegance to your home.',
        6,
        38,
        520,
        27,
        'Stone Grey',
        '/images/products/trays/tray_3.jpg',
        7,
        2
    ),
    (
        'Tray Eclipse',
        'M',
        220,
        'Bold and balanced, Eclipse plays with contrast and form. Its unique silhouette casts captivating shadows, elevating your décor effortlessly.',
        5,
        32,
        410,
        24,
        'Charcoal Grey',
        '/images/products/trays/tray_4.jpg',
        9,
        2
    ),
    (
        'Tray Nimbus',
        'XL',
        230,
        'Light as a cloud, strong as stone. Nimbus combines soft curves with a solid presence, bringing tranquility and sophistication to any setting.',
        7,
        45,
        680,
        32,
        'Cloud Grey',
        '/images/products/trays/tray_5.jpg',
        5,
        2
    ),
    (
        'Tray Aurea',
        'S',
        180,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        4,
        27,
        300,
        20,
        'Sand',
        '/images/products/trays/tray_6.jpg',
        13,
        2
    );