INSERT INTO products (
    name,
    size,
    price,
    description,
    height,
    width,
    weight,
    length,
    color,
    url_image,
    amount,
    category_id
)
VALUES
    (
        'Vase Lunar',
        'S',
        190,
        'Sculptural and serene, Lunar embraces light within its soft curves. A modern centerpiece that brings warmth and balance to any space.',
        18,
        10,
        650,
        10,
        'Light Grey',
        '/images/products/vases/vase_1.jpg',
        14,
        1
    ),
    (
        'Vase Orbit',
        'M',
        200,
        'Inspired by celestial motion, Orbit features a smooth, rounded form that cradles light beautifully. Perfect for modern, minimalist interiors.',
        24,
        13,
        950,
        13,
        'Warm Grey',
        '/images/products/vases/vase_2.jpg',
        9,
        1
    ),
    (
        'Vase Haven',
        'L',
        220,
        'A cozy retreat for candlelight. Haven’s organic shape creates a calming atmosphere, adding a touch of natural elegance to your home.',
        30,
        16,
        1250,
        16,
        'Sand',
        '/images/products/vases/vase_3.jpg',
        7,
        1
    ),
    (
        'Vase Eclipse',
        'XL',
        180,
        'Bold and balanced, Eclipse plays with contrast and form. Its unique silhouette casts captivating shadows, elevating your décor effortlessly.',
        38,
        19,
        1750,
        19,
        'Charcoal Grey',
        '/images/products/vases/vase_4.jpg',
        5,
        1
    ),
    (
        'Vase Nimbus',
        'M',
        145,
        'Light as a cloud, strong as stone. Nimbus combines soft curves with a solid presence, bringing tranquility and sophistication to any setting.',
        27,
        14,
        1100,
        14,
        'Stone Grey',
        '/images/products/vases/vase_5.jpg',
        8,
        1
    ),
    (
        'Vase Aurea',
        'L',
        260,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        32,
        17,
        1400,
        17,
        'Ivory',
        '/images/products/vases/vase_6.jpg',
        6,
        1
    ),
    (
        'Vase Soleil',
        'S',
        195,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        20,
        11,
        720,
        11,
        'Cream',
        '/images/products/vases/vase_7.jpg',
        12,
        1
    ),
    (
        'Vase Terra',
        'XL',
        220,
        'Timeless and refined, Aurea reflects the beauty of golden light. Its minimalist design enhances warm, inviting atmospheres with subtle luxury.',
        41,
        21,
        1950,
        21,
        'Terracotta',
        '/images/products/vases/vase_8.jpg',
        4,
        1
    );